# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: etcd3/rpc/auth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x14\x65tcd3/rpc/auth.proto\x12\x06\x61uthpb"1\n\x0eUserAddOptions\x12\x1f\n\x0bno_password\x18\x01 \x01(\x08R\nnoPassword"~\n\x04User\x12\x12\n\x04name\x18\x01 \x01(\x0cR\x04name\x12\x1a\n\x08password\x18\x02 \x01(\x0cR\x08password\x12\x14\n\x05roles\x18\x03 \x03(\tR\x05roles\x12\x30\n\x07options\x18\x04 \x01(\x0b\x32\x16.authpb.UserAddOptionsR\x07options"\x9c\x01\n\nPermission\x12\x33\n\x08permType\x18\x01 \x01(\x0e\x32\x17.authpb.Permission.TypeR\x08permType\x12\x10\n\x03key\x18\x02 \x01(\x0cR\x03key\x12\x1b\n\trange_end\x18\x03 \x01(\x0cR\x08rangeEnd"*\n\x04Type\x12\x08\n\x04READ\x10\x00\x12\t\n\x05WRITE\x10\x01\x12\r\n\tREADWRITE\x10\x02"T\n\x04Role\x12\x12\n\x04name\x18\x01 \x01(\x0cR\x04name\x12\x38\n\rkeyPermission\x18\x02 \x03(\x0b\x32\x12.authpb.PermissionR\rkeyPermissionBO\n\ncom.authpbB\tAuthProtoP\x01\xa2\x02\x03\x41XX\xaa\x02\x06\x41uthpb\xca\x02\x06\x41uthpb\xe2\x02\x12\x41uthpb\\GPBMetadata\xea\x02\x06\x41uthpbb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "etcd3.rpc.auth_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"\n\ncom.authpbB\tAuthProtoP\001\242\002\003AXX\252\002\006Authpb\312\002\006Authpb\342\002\022Authpb\\GPBMetadata\352\002\006Authpb"
    _USERADDOPTIONS._serialized_start = 32
    _USERADDOPTIONS._serialized_end = 81
    _USER._serialized_start = 83
    _USER._serialized_end = 209
    _PERMISSION._serialized_start = 212
    _PERMISSION._serialized_end = 368
    _PERMISSION_TYPE._serialized_start = 326
    _PERMISSION_TYPE._serialized_end = 368
    _ROLE._serialized_start = 370
    _ROLE._serialized_end = 454
# @@protoc_insertion_point(module_scope)
