"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class RaftAttributes(google.protobuf.message.Message):
    """RaftAttributes represents the raft related attributes of an etcd member."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PEER_URLS_FIELD_NUMBER: builtins.int
    IS_LEARNER_FIELD_NUMBER: builtins.int
    is_learner: builtins.bool
    """isLearner indicates if the member is raft learner."""
    @property
    def peer_urls(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """peerURLs is the list of peers in the raft cluster."""

    def __init__(
        self,
        *,
        peer_urls: collections.abc.Iterable[builtins.str] | None = ...,
        is_learner: builtins.bool = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "is_learner", b"is_learner", "peer_urls", b"peer_urls"
        ],
    ) -> None: ...

global___RaftAttributes = RaftAttributes

@typing.final
class Attributes(google.protobuf.message.Message):
    """Attributes represents all the non-raft related attributes of an etcd member."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    CLIENT_URLS_FIELD_NUMBER: builtins.int
    name: builtins.str
    @property
    def client_urls(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[
        builtins.str
    ]: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        client_urls: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing.Literal["client_urls", b"client_urls", "name", b"name"]
    ) -> None: ...

global___Attributes = Attributes

@typing.final
class Member(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    RAFT_ATTRIBUTES_FIELD_NUMBER: builtins.int
    MEMBER_ATTRIBUTES_FIELD_NUMBER: builtins.int
    ID: builtins.int
    @property
    def raft_attributes(self) -> global___RaftAttributes: ...
    @property
    def member_attributes(self) -> global___Attributes: ...
    def __init__(
        self,
        *,
        ID: builtins.int = ...,
        raft_attributes: global___RaftAttributes | None = ...,
        member_attributes: global___Attributes | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "member_attributes",
            b"member_attributes",
            "raft_attributes",
            b"raft_attributes",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "ID",
            b"ID",
            "member_attributes",
            b"member_attributes",
            "raft_attributes",
            b"raft_attributes",
        ],
    ) -> None: ...

global___Member = Member

@typing.final
class ClusterVersionSetRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VER_FIELD_NUMBER: builtins.int
    ver: builtins.str
    def __init__(
        self,
        *,
        ver: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ver", b"ver"]) -> None: ...

global___ClusterVersionSetRequest = ClusterVersionSetRequest

@typing.final
class ClusterMemberAttrSetRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MEMBER_ID_FIELD_NUMBER: builtins.int
    MEMBER_ATTRIBUTES_FIELD_NUMBER: builtins.int
    member_ID: builtins.int
    @property
    def member_attributes(self) -> global___Attributes: ...
    def __init__(
        self,
        *,
        member_ID: builtins.int = ...,
        member_attributes: global___Attributes | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["member_attributes", b"member_attributes"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "member_ID", b"member_ID", "member_attributes", b"member_attributes"
        ],
    ) -> None: ...

global___ClusterMemberAttrSetRequest = ClusterMemberAttrSetRequest

@typing.final
class DowngradeInfoSetRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENABLED_FIELD_NUMBER: builtins.int
    VER_FIELD_NUMBER: builtins.int
    enabled: builtins.bool
    ver: builtins.str
    def __init__(
        self,
        *,
        enabled: builtins.bool = ...,
        ver: builtins.str = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing.Literal["enabled", b"enabled", "ver", b"ver"]
    ) -> None: ...

global___DowngradeInfoSetRequest = DowngradeInfoSetRequest
