# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: etcd3/rpc/membership.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from etcd3.rpc import version_pb2 as etcd3_dot_rpc_dot_version__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1a\x65tcd3/rpc/membership.proto\x12\x0cmembershippb\x1a\x17\x65tcd3/rpc/version.proto"U\n\x0eRaftAttributes\x12\x1b\n\tpeer_urls\x18\x01 \x03(\tR\x08peerUrls\x12\x1d\n\nis_learner\x18\x02 \x01(\x08R\tisLearner:\x07\x82\xb5\x18\x03\x33.5"J\n\nAttributes\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n\x0b\x63lient_urls\x18\x02 \x03(\tR\nclientUrls:\x07\x82\xb5\x18\x03\x33.5"\xaf\x01\n\x06Member\x12\x0e\n\x02ID\x18\x01 \x01(\x04R\x02ID\x12\x45\n\x0fraft_attributes\x18\x02 \x01(\x0b\x32\x1c.membershippb.RaftAttributesR\x0eraftAttributes\x12\x45\n\x11member_attributes\x18\x03 \x01(\x0b\x32\x18.membershippb.AttributesR\x10memberAttributes:\x07\x82\xb5\x18\x03\x33.5"5\n\x18\x43lusterVersionSetRequest\x12\x10\n\x03ver\x18\x01 \x01(\tR\x03ver:\x07\x82\xb5\x18\x03\x33.5"\x8a\x01\n\x1b\x43lusterMemberAttrSetRequest\x12\x1b\n\tmember_ID\x18\x01 \x01(\x04R\x08memberID\x12\x45\n\x11member_attributes\x18\x02 \x01(\x0b\x32\x18.membershippb.AttributesR\x10memberAttributes:\x07\x82\xb5\x18\x03\x33.5"N\n\x17\x44owngradeInfoSetRequest\x12\x18\n\x07\x65nabled\x18\x01 \x01(\x08R\x07\x65nabled\x12\x10\n\x03ver\x18\x02 \x01(\tR\x03ver:\x07\x82\xb5\x18\x03\x33.5Bs\n\x10\x63om.membershippbB\x0fMembershipProtoP\x01\xa2\x02\x03MXX\xaa\x02\x0cMembershippb\xca\x02\x0cMembershippb\xe2\x02\x18Membershippb\\GPBMetadata\xea\x02\x0cMembershippbb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "etcd3.rpc.membership_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"\n\020com.membershippbB\017MembershipProtoP\001\242\002\003MXX\252\002\014Membershippb\312\002\014Membershippb\342\002\030Membershippb\\GPBMetadata\352\002\014Membershippb"
    _RAFTATTRIBUTES._options = None
    _RAFTATTRIBUTES._serialized_options = b"\202\265\030\0033.5"
    _ATTRIBUTES._options = None
    _ATTRIBUTES._serialized_options = b"\202\265\030\0033.5"
    _MEMBER._options = None
    _MEMBER._serialized_options = b"\202\265\030\0033.5"
    _CLUSTERVERSIONSETREQUEST._options = None
    _CLUSTERVERSIONSETREQUEST._serialized_options = b"\202\265\030\0033.5"
    _CLUSTERMEMBERATTRSETREQUEST._options = None
    _CLUSTERMEMBERATTRSETREQUEST._serialized_options = b"\202\265\030\0033.5"
    _DOWNGRADEINFOSETREQUEST._options = None
    _DOWNGRADEINFOSETREQUEST._serialized_options = b"\202\265\030\0033.5"
    _RAFTATTRIBUTES._serialized_start = 69
    _RAFTATTRIBUTES._serialized_end = 154
    _ATTRIBUTES._serialized_start = 156
    _ATTRIBUTES._serialized_end = 230
    _MEMBER._serialized_start = 233
    _MEMBER._serialized_end = 408
    _CLUSTERVERSIONSETREQUEST._serialized_start = 410
    _CLUSTERVERSIONSETREQUEST._serialized_end = 463
    _CLUSTERMEMBERATTRSETREQUEST._serialized_start = 466
    _CLUSTERMEMBERATTRSETREQUEST._serialized_end = 604
    _DOWNGRADEINFOSETREQUEST._serialized_start = 606
    _DOWNGRADEINFOSETREQUEST._serialized_end = 684
# @@protoc_insertion_point(module_scope)
