"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.descriptor_pb2
import google.protobuf.internal.extension_dict

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

ETCD_VERSION_MSG_FIELD_NUMBER: builtins.int
ETCD_VERSION_FIELD_FIELD_NUMBER: builtins.int
ETCD_VERSION_ENUM_FIELD_NUMBER: builtins.int
ETCD_VERSION_ENUM_VALUE_FIELD_NUMBER: builtins.int
etcd_version_msg: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[
    google.protobuf.descriptor_pb2.MessageOptions, builtins.str
]
etcd_version_field: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[
    google.protobuf.descriptor_pb2.FieldOptions, builtins.str
]
etcd_version_enum: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[
    google.protobuf.descriptor_pb2.EnumOptions, builtins.str
]
etcd_version_enum_value: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[
    google.protobuf.descriptor_pb2.EnumValueOptions, builtins.str
]
